services:
  - type: web
    name: telegram-selfbot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: SESSION_STRING
        sync: false
      - key: HELPER_USERNAME
        value: Sa1selfbot
      - key: SUPPORT_USERNAME
        value: Saleh681
